In [3]:
import numpy as np
arr=np.array(range(72))
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71])

In [4]:
arr.reshape(2,2,3,6)

array([[[[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11],
         [12, 13, 14, 15, 16, 17]],

        [[18, 19, 20, 21, 22, 23],
         [24, 25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34, 35]]],


       [[[36, 37, 38, 39, 40, 41],
         [42, 43, 44, 45, 46, 47],
         [48, 49, 50, 51, 52, 53]],

        [[54, 55, 56, 57, 58, 59],
         [60, 61, 62, 63, 64, 65],
         [66, 67, 68, 69, 70, 71]]]])

In [9]:
arr0=np.identity(10)
arr0

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [11]:
arr1=np.zeros((2,5))
arr1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
import numpy as np
arr2=np.array(range(240))
arr3=arr2.reshape(2,2,3,4,5)
#0,177,71,240
arr4 =arr3 [1,0,2,3,2]
arr4

np.int64(177)

In [12]:
import numpy as np
arr5=np.array(range(288))
arr6=arr5.reshape(2,3,2,6,4)
# 1

arr7= arr6 [1,1,1,0,3]
arr7

np.int64(219)

In [23]:
arr=np.array(range(30)).reshape(5,6)
arr[3:,4:]

array([[22, 23],
       [28, 29]])

In [ ]:
# Filter and Where

In [2]:
import numpy as np
tbt=np.array(([10,20,30,40]))
ar=tbt[(tbt>10) & (tbt<40)]
ar

array([20, 30])

In [3]:
import pandas as pd
sr=pd.Series(['1','2','3'])
sr

0    1
1    2
2    3
dtype: str

In [ ]:
import pandas as pd
userData={'name':['Sheheryar','Ali','Subhani'],'age':[21,23,20]}
df=pd.DataFrame(userData)
df
#df.to_csv('Class First Table')

In [8]:
import pandas as pd
userData={'Name':['Ali','Sheheryar','Ahmad'],'age':[20,25,30],'Class':['Pyhton','C','V'] }
df1=pd.DataFrame(userData)
df1.to_csv('UserData.csv')
df1

        Name  age   Class
0        Ali   20  Pyhton
1  Sheheryar   25       C
2      Ahmad   30       V

In [6]:
import openpyxl as opx
df=pd.read_excel('VendorProducts.xlsx')
df

,Picture,Id,Name,Secondary Name,Barcode,Code,Price,Description,Secondary Description,Sub Description,Secondary Sub Description,Menu,Brand,Secondary Brand,Has Collections
0,https://www.storeakmedia.com/storeak-erp/Store...,390188,زيت الشفاه بليجر 001، 5 مل,"Pleasure Lip Oil 001, 5 ml",8011607402304,NaN,"25,000د.ع","زيت مغذي للشفاه, يُعزز لمعان الشفاه بتأثير بصر...",Nourishing lip oil that enhances lip shine wit...,|بوبا ميلانو|Pupa Milano|Lip Oil|زيت الشفاه|زي...,NaN,العناية بالبشرة‎ -> الشفاه‎ -> زيوت,بوبا ميلانو,Pupa Milano,No
1,https://www.storeakmedia.com/storeak-erp/Store...,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,NaN,"300,000د.ع",عطر أروماتك إنيق للرجال.\nمكونات العطر: العنبر...,An elegant aromatic fragrance for men.\nFragra...,|شانيل|Chanel|العطور|Perfumes|عطر للرجال|عطر ر...,NaN,"العطور‎ -> رجالي‎ -> العطور,private group‎ -> ...",شانيل,Chanel,Yes
2,https://www.storeakmedia.com/storeak-erp/Store...,390186,سيروم الشعر لفروة الرأس سيابوري 20 مل,Seapuri Scalpy Hair Serum 20 ml,8809934860870,NaN,"30,000د.ع",سيروم خفيف الوزن وغير دهني يعالج تساقط الشعر و...,"A lightweight, non greasy serum that treats ha...",|Others|اخرى|hair loss Serum|سيروم تساقط الشعر...,NaN,الشعر‎ -> العناية بالشعر‎ -> تساقط الشعر‎ -> س...,اخرى,Others,No
3,https://www.storeakmedia.com/storeak-erp/Store...,390185,عطر جانيميد اودي بارفيوم 50 مل,Ganymede EDP 50 ml,3770006409141,NaN,00د.ع,"عطر شرقي حار للجنسين.\nمقدمة العطر: البخور, ال...",An oriental spicy fragrance for both sexes.\nT...,|Marc-Antoine Barois Paris|مارك أنطوان باروا ب...,NaN,"العطور‎ -> نسائي‎ -> العطور,العطور‎ -> رجالي‎ ...",مارك انطوان باروا باريس,Marc-Antoine Barrois Paris,No
4,https://www.storeakmedia.com/storeak-erp/Store...,390177,جل تصفيف الحواجب مع الببتيدات 15 مل,Brow Styling Gel With Peptides 15 ml,8056814230036,NaN,"15,000د.ع",امنحي حواجبك شكلاً أنيقًا يدوم طوال اليوم مع ج...,"Give your brows a sleek, all day shape with ou...",|Ayten|أيتن|Eyebrow Gel|جل الحواجب|جل تصفيف ال...,NaN,المكياج‎ -> الحواجب‎ -> جل,آيتن,Ayten,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24697,https://www.storeakmedia.com/storeak-erp/Store...,315019,معطر الشعر والجسم بالليمون والماتشا 150 مل,Lime & Matcha Hair & Body Mist 150 ml,5028197838058,0,"16,500د.ع","زذاذ معطر الجسم والشعر منعش وفواح, يتكون من مز...","A refreshing and fragrant body and hair mist, ...",|ذا بودي شوب|The Body Shop|عطور الشعر|Hair Per...,NaN,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24698,https://www.storeakmedia.com/storeak-erp/Store...,315018,معطر الشعر والجسم بالفلفل الوردي والليتشي 150 مل,Pink Pepper & Lychee Hair & Body Mist 150 ml,5028197930516,0,"12,000د.ع","رذاذ معطر الجسم والشعر جذاب ومنعش للنساء, يمتا...",An attractive and refreshing body and hair mis...,|ذا بودي شوب|The Body Shop|عطور الشعر|Hair Per...,NaN,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24699,https://www.storeakmedia.com/storeak-erp/Store...,314993,ماسكارا جلام اند دول تعزز نمو الرموش 8 مل,Glam & Doll Boost Lash Growth Volume Mascara 8 ml,4059729191380,0,"10,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...","Mascara features a brush with thick bristles, ...",|كاتريس|Catrice|ماسكارا عادية| Mascara‎ Normal...,NaN,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,كاتريس,Catrice,No
24700,https://www.storeakmedia.com/storeak-erp/Store...,314992,مست الجسم باشن فروت 150 مل,Body Mist Passion Fruit150 ml,5283024103017,0,"15,000د.ع","رذاذ معطر للجسم, يساعدك على الشعور بالانتعاش و...",A body mist that helps you feel fresh and conf...,|بيت الصابون اللبناني|Bayt Al Saboun|العناية ب...,NaN,"العناية بالجسم‎ -> سبلاش,private group‎ -> مين...",بيت الصابون اللبناني,Bayt Al Saboun,No
24701,https://www.storeakmedia.com/storeak-erp/Store...,314991,ماسكارا فائقة الكثافة (1أسود) 15 مل,Volume Supreme Mascara (1Black) 15 ml,4052136039429,0,"22,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...",Mascara is characterized by its thick bristled...,|آرتديكو|Artdeco|ماسكارا عادية| Mascara‎ Norma...,NaN,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,آرتديكو,Artdeco,No

In [10]:
#Create Banking System
user=[]
print('Welcome to the banking system')
while(true):
    if(user==Data)

KeyboardInterrupt:

In [7]:
import pandas as pd
# Create account
name = input("Enter name: ")
age = int(input("Enter age: "))
balance = 5000
data = {
    "Name":[name],
    "Age":[age],
    "Balance":[balance]
}
df = pd.DataFrame(data)
df.to_csv("bank.csv",index=False)
while True:
    print("\n1 Check Balance")
    print("2 Deposit")
    print("3 Withdraw")
    print("4 Exit")
    choice = input("Enter choice: ")
    if choice == "1":
        print("Balance:", balance)
    elif choice == "2":
        amount = int(input("Enter deposit amount: "))
        balance = balance + amount
        print("Deposit successful")
    elif choice == "3":
        amount = int(input("Enter withdraw amount: "))
        if amount <= balance:
            balance = balance - amount
            print("Withdraw successful")
        else:
            print("Not enough balance")
    elif choice == "4":
        df["Balance"] = balance
        df.to_csv("bank.csv",index=False)
        print("Data saved in CSV")
        break

1 Check Balance
2 Deposit
3 Withdraw
4 Exit
Deposit successful

1 Check Balance
2 Deposit
3 Withdraw
4 Exit
Data saved in CSV